title: Formal Methods Little Corner
author: Roberto Bruttomesso
email: roberto.bruttomesso@gmail.com
description: >
  Tools and algorithms for verification, test generation, equivalence checking, etc.

github_username:  formalmethods

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

google_analytics: UA-106780132-1

disqus:
    shortname: formalmethods

header_pages:
  - about.md
#  - consulting.md

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
future: true
